ARG SYSBASE=almalinux
FROM ${SYSBASE} as builder
ARG ARCH=x86_64
RUN mkdir /mnt/sysimage; \
    dnf install \
    --nogpgcheck --repoid=AppStream --repoid=BaseOS \
    --repofrompath='BaseOS,https://repo.almalinux.org/almalinux/8.5/BaseOS/x86_64/os/' \
    --repofrompath='AppStream,https://repo.almalinux.org/almalinux/8.5/AppStream/x86_64/os/' \
    --installroot /mnt/sysimage \
    --releasever 8 \
    --setopt install_weak_deps=false \
    --nodocs -y \
    binutils \
    coreutils-single \
    dnf \
    findutils \
    glibc-minimal-langpack \ 
    hostname \
    iputils \
    langpacks-en \
    less \
    libcurl-minimal \
    rootfiles \
    tar \
    vim-minimal \
    yum \
    xz \ 
    ; \
    dnf --installroot /mnt/sysimage clean all; \
    rm -rf /mnt/sysimage/var/log/dnf* /mnt/sysimage/var/log/yum.*; \
    rm -rf /mnt/sysimage/var/lib/dnf/history* /mnt/sysimage/var/log/hawkey.log  /mnt/sysimage/boot /mnt/sysimage/dev/null /mnt/sysimage/run/*; \
    mkdir -p /mnt/sysimage/run/lock; \
    # rm -rf /mnt/sysimage/var/cache/*  removed line
    # cp /etc/yum.repos.d/*.repo /mnt/sysimage/etc/yum.repos.d/; \
    # generate build time file for compatibility with CentOS
    /bin/date +%Y%m%d_%H%M > /mnt/sysimage/etc/BUILDTIME; \
    echo '%_install_langs C.utf8' > /mnt/sysimage/etc/rpm/macros.image-language-conf; \
    echo 'LANG="C.utf8"' >  /mnt/sysimage/etc/locale.conf; \
    echo 'container' > /mnt/sysimage/etc/dnf/vars/infra; \
    rm -f /mnt/sysimage/etc/machine-id; \
    touch /mnt/sysimage/etc/machine-id;

# Almalinux minimal build
FROM scratch 
COPY --from=builder /mnt/sysimage/ /

CMD ["/bin/bash"]
